export type FontSizeType = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl'
export type VariantTypes = 'default' | 'current' | 'primary'
export type SpacingTypes = 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl'
export type HeightTypes = 'half' | 'full' | 'screen'
export type WidthTypes =
  | 'xs'
  | 'sm'
  | 'md'
  | 'lg'
  | 'xl'
  | '2xl'
  | '3xl'
  | 'half'
  | 'full'
  | 'screen'
export type FlexDirectionTypes = 'row' | 'column' | 'row-reverse' | 'column-reverse'
export type AlignItemTypes = 'center' | 'start' | 'end' | 'baseline' | 'stretch'
export type JustifyContentTypes =
  | 'center'
  | 'start'
  | 'end'
  | 'between'
  | 'around'
  | 'evenly'
export type FontWeightTypes =
  | 'thin'
  | 'extralight'
  | 'light'
  | 'normal'
  | 'medium'
  | 'semibold'
  | 'bold'
  | 'extrabold'
  | 'black'
